name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        
        - name: chechout reto
          uses: actions/checkout@v4

        - name: Welcome Message
          run: echo "Welcome to GitHub Actions"
        
        - name: list files
          run: ls

        - name: cat file
          run: cat README.md
        